swagger: '2.0'
info:
  description: Demo Mockx
  version: 1.0.0
  title: Demo Mock

host: virtserver.swaggerhub.com
basePath: /CothamTechnologies/DemoMock1/1.0.0
schemes:
 - https

paths:
  
  /generalData:
    get:
      summary: generalData
      description: generalData
      tags:
        - General
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              attr1:
                type: string
                example: attribute 1 Data
              attr2:
                type: string
                example: attribute 2 Data
              attr3:
                type: string
                example: attribute 1 Data
              attr4:
                type: string
                example: attribute 2 Data
        default:
          description: server error
  
  /fueltypes:
    get:
      summary: Get Fuel Types
      description: Get Fuel Types
      tags:
        - Crowe Mackay
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                description: 
                  type: string
                              
            example:
              - description: Regular
              - description: Supreme
              - description: Diesel

        default:
          description: server error
  

  
  /vehiclemetadata:
    get:
      summary: get vehicle meta data
      description: get vehicle makes - models 
      tags:
        - Crowe Mackay
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                makeName: 
                  type: string
                model:
                  type: array
                  items:
                    type: object
                    properties:
                      modelName:
                        type: string
            example:
              - makeName: Audi
                model:
                  - modelName: Audi model 1
                  - modelName: Audi model 2
                  - modelName: Audi model 3
              - makeName: Jaguar
                model:
                  - modelName: Jaguar model 1
                  - modelName: Jaguar model 2
                  - modelName: Jaguar model 3
              - makeName: Porche
                model:
                  - modelName: Porche model 1
                  - modelName: Porche model 2
                  - modelName: Porche model 3
              - makeName: VW
                model:
                  - modelName: VW model 1
                  - modelName: VW model 2
                  - modelName: VW model 3
              - makeName: Ford
                model:
                  - modelName: Ford model 2
                  - modelName: Ford model 3
              - makeName: Honda
                model:
                  - modelName: Honda model 1
                  - modelName: Honda model 2
                  - modelName: Honda model 3


        default:
          description: server error
  
  /vehicles:
    get:
      summary: Get vehicles
      description: Get vehicles
      tags:
        - Crowe Mackay
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                registration:
                  type: string
                make:
                  type: string
                model:
                  type: string
                fueltype:
                  type: string
                capacity:
                  type: number

            example:
              - registration: FT11 YOL
                make: Audi
                model: Audi Model 1
                fueltype: Diesel
                capacity: 65
              - registration: DR13 SDL
                make: Jaguar
                model: Jaguar Model 3
                fueltype: Regular
                capacity: 75

        default:
          description: server error
  
  /fuelprices:
    get:
      summary: Get fuel prices
      description: Get fuel prices
      tags:
        - Crowe Mackay
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                fueltype:
                  type: string
                price:
                  type: string
            example:
              - fueltype: Regular
                price: 172.9
              - fueltype: Supreme
                price: 192.9
              - fueltype: Diesel
                price: 154.9

        default:
          description: server error
  
  /tankvehicle:
    get:
      summary: get tank vehicle list
      description: get tank vehicle list
      tags:
        - Crowe Mackay
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                vehicletank:
                  type: string

            example:
              - vehicletank: Tank
              - vehicletank: Vehicle


        default:
          description: server error
  
 
  /salutations:
    get:
      summary: salutations
      description: salutations
      tags:
        - General
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string

            example:
              - name: Mr
              - name: Ms
              - name: Miss
              - name: Mrs


        default:
          description: server error
  
  /addresstype:
    get:
      summary: addresstype
      description: addresstype
      tags:
        - General
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string

            example:
              - name: Delivery
              - name: Billing



        default:
          description: server error
  
  /login:
    get:
      summary: login
      description: login
      tags:
        - General
      produces:
      - application/json
      parameters:
      - in: query
        name: email
        type: string
        description: email
        required: true
      - in: query
        name: password
        type: string
        description: password
        required: true 
     
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
                example: hdjhjdhjfdhjdfhjfd878&&
              expiry:
                type: string
                example: 4097174399
        default:
          description: server error